### ISSUE TITLE
Add revisions

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/multiple-content-blocks#28]
https://lud.icro.us/post-meta-revisions-wordpress

**Comment by mattsince87** [comment]
Apologies if this is blindingly obvious, but how can i remove a content block once it has been defined in the page template? It keeps showing up on the wordpress admin/page editor

**Comment by haroldangenent** [comment]
Will not be adding revisions or any other features to this plugin for that matter. Closing this issue.
