### ISSUE TITLE
Can't delete multiple content blocks

### ISSUE THREAD

**Issue by cecilehabran** [trendwerk/multiple-content-blocks#61]
I removed some blocks from my template page and add others. The new blocks are displayed in the back office but the old ones are still there. How can I delete them?

Thanks!

**Comment by KWaldt** [comment]
Hello there!

I have the same problem--new blocks get created, but old ones aren't deleted even if I remove them from code.
Would you like me to send you my code, or do you have any idea how to solve this?
(A button to refresh the post cache or something, maybe?)

Best Regards,
Kristina Waldt

**Comment by JimboTSoV** [comment]
So.. I'm guessing the support for this has been stopped? Nonetheless I would like to adress that this is still a problem.

**Comment by haroldangenent** [comment]
We're still trying to answer as many questions about the plugin as possible, but the plugin is not in active development anymore. I would recommend using [Advanced Custom Fields](http://www.advancedcustomfields.com/).
