### ISSUE TITLE
Static Home Page with Multiple Blocks

### ISSUE THREAD

**Issue by charasan** [trendwerk/multiple-content-blocks#64]
If the page in question is your home page, the multiple blocks don't get recognized on the home page. Go to the page directly and they'll be there.

**Comment by haroldangenent** [comment]
Just tested this on a clean install with a page on front. Seems to be working (was fixed in #37).

Can you reproduce this on a clean install?

**Comment by charasan** [comment]
Sorry, just realized they're using WooThemes, and it may be overriding the template I was using for the page. Sorry to bother you. :}
