### ISSUE TITLE
Always writing to db?

### ISSUE THREAD

**Issue by GrimaceOfDespair** [trendwerk/multiple-content-blocks#70]
When just viewing a page, it seems that MCB always writes to the database. Is this intended behaviour?

![image](https://cloud.githubusercontent.com/assets/228782/10558160/5ffe7618-74c6-11e5-81fc-dd505ccd256d.png)

![image](https://cloud.githubusercontent.com/assets/228782/10558179/f04e6f02-74c6-11e5-8be4-f269371dc467.png)

**Comment by haroldangenent** [comment]
Yes. There's no other way to reliably define what blocks should be used on a page. More information can be found here: https://github.com/trendwerk/multiple-content-blocks/issues/54#issuecomment-54327005.

Not an ideal situation, so when this detail of performance is interesting, I would recommend registering your own meta boxes or using a plugin like Advanced Custom Fields. These options are less dynamic and you will have to define your blocks beforehand, but this increases performance.
