### ISSUE TITLE
Multiple content box loses data when you update a post/page

### ISSUE THREAD

**Issue by bryhsu151** [trendwerk/multiple-content-blocks#71]
I am experience and issue with this plugin. Whenever I try to update a post/page and I hit update. It wipes out the entries from the database. I tried to update 1 page today, and then i searched the page ID in MySQL and all the extra box contents become completely blank.

**Comment by haroldangenent** [comment]
I cannot reproduce this issue. Does this also happen on a clean install?

If so, could you provide me some steps to reproduce this problem?

**Comment by bryhsu151** [comment]
Well in the recent months, WordPress has moved servers and IPs have been changed. WordPress has gone through many updates including the plugin. The old server uses and old version of the plugin 2.2.1 while the new server is the most updated 3.2.2. The old plugin from the old server works like a charm, but after the move updating previous existing posts with multiple content blocks. It would wipe out the c2 or c3 columns which is where the content would be stored.

**Comment by haroldangenent** [comment]
I'm not sure I could figure out what's going on based on this information. It seems like there's a lot of stuff going on, not specifically related to the plugin.

For your problem, I would advice to use your own meta boxes or dive into the problem a little deeper. If you find any bugs in the plugin, let me know.
