### ISSUE TITLE
Non-latin block name causes WP editor error

### ISSUE THREAD

**Issue by velosipedist** [trendwerk/multiple-content-blocks#73]
Occurs at WP 4.4 and plugin 3.2.2

When i use `the_block('Правая колонка')`, wp page editor at admin backend raises error instead of howing block editor.

**Comment by haroldangenent** [comment]
Could you try using the `label` option? The unique identifier should not contain any special characters, since it's also used for identifying the block in de admin panel.

```
the_block('block-id', array(
  'label' => 'Правая колонка',
));
```
